Update configparser version requirement to build with CentOS 7
esnet/tstat-transport pull request #10
Opened 2017-04-21 20:21 UTC by apertome

We were unable to build on CentOS 7 because the setup.py file specifies `python-configparser == 3.5.0` while CentOS 7 provides `python-configparser.noarch 0:3.5.0b2-1.el7`

This change to setup.py fixes that issue.

2017-04-24 15:11 UTC, montegoode requested changes
Bumping the version of configparser is totally fine, but please peg it to a specific version. Which is to say == it to a specific version that will work with CentOS 7, don't use the >=.

The reason for this is that having pip reflexively pull down the most recent version can potentially cause trouble.

2017-04-24 21:25 UTC, apertome commented
I changed it to a specific version:  'configparser==3.5.0b2', but I don't know if this will be a valid choice with different distros, python versions, etc. It seems to be valid for CentOS 6 and 7 as far as I can see, but I don't know if there is a reason it was '3.5.0' specifically before.

We could do something like:
">=3.5.0,<3.5.1"if we wanted to be more flexible (CentOS at least seems to think 3.5.0b2 is greater than 3.5.0).

Thanks.

2017-04-25 20:37 UTC, montegoode commented
@apertome It was pegged to 3.5.0 originally because that was the current version at the time. The thought being that every installation of specific version will all be using the same version of third party dependencies. If third party libraries are not pegged to specific versions, then when a package is deployed at a later date, then it might be using a different version of a dependency and this can cause problems if issues arise. It's a great source of the "well it works on my machine" bug nightmares.

I don't totally understand why it matters what version is already installed on the CentOS machine? Normally when you deploy a package with pip, it looks at `setup.py` and deploys whatever version of the dependencies are listed there. It should just pull stuff down from PyPI. Which is to say, executing:

```
pip install tstat-transport
```
Should be a self-contained process that installs the `tstat-transport` package and all of its dependencies at the versions listed. What is already on the machine shouldn't matter.

Is there some other issue?

2017-04-25 20:42 UTC, apertome commented
We don't deploy with pip, we deploy with RPMs, and 3.5.0 is not available in the CentOS 6 or CentOS 7 EPEL RPMs, only 3.5.0b2, which does not satisfy the 3.5.0 requirement.

2017-04-25 20:47 UTC, montegoode commented
I don't think it will be an issue to peg the version to b2. This worked fine:

```
Downloading/unpacking configparser==3.5.0b2 (from -r requirements.txt (line 1))
  Downloading configparser-3.5.0b2.tar.gz
  Storing download in cache at /Users/monte/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F61%2Fa7%2F48f627413200d5dfd0a5da8b494d34ccac03f8a87a6b2d765b7d81e175e3%2Fconfigparser-3.5.0b2.tar.gz
  Running setup.py (path:/Users/monte/Desktop/tmp/venv/build/configparser/setup.py) egg_info for package configparser
    
Installing collected packages: configparser
  Running setup.py install for configparser
```
It is, as far as I can tell, the most recent version of the library.

2017-04-25 20:48 UTC, montegoode approved these changes

2017-04-25 20:49 UTC, merged

2017-04-25 20:51 UTC, apertome commented
Sounds good -- thanks!